apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-queue-scale
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-queue-scale
  template:
    metadata:
      labels:
        app: nginx-queue-scale
    spec:
      serviceAccountName: keda-queue-sa
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

